/** Scoped right-tab geometry using the host's light/dark semantic tokens. */
export const styles = `
.dsh-checkin{--ci-bg:var(--dsw-alias-bg-base);--ci-fg:var(--dsw-alias-label-primary);--ci-muted:var(--dsw-alias-label-secondary);color:var(--ci-fg);font:inherit;font-size:14px;line-height:1.5;box-sizing:border-box}
.dsh-checkin *{box-sizing:border-box}.dsh-checkin button,.dsh-checkin input,.dsh-checkin select{font:inherit;color:inherit}.dsh-checkin button{cursor:pointer}.dsh-checkin button:disabled{cursor:default;opacity:.45}.dsh-checkin :focus-visible{outline:2px solid var(--dsw-alias-label-primary);outline-offset:3px}.dsh-checkin ::selection{background:var(--dsw-alias-interactive-bg-active)}
.ci-trigger{display:inline-flex;align-items:center;gap:8px;height:42px;padding:0 10px 0 8px;background:transparent;border:0;border-radius:12px;white-space:nowrap;color:var(--dsw-alias-label-primary);font:inherit;font-size:14px;line-height:22px;cursor:pointer}.ci-trigger[data-wide=true]{width:100%;justify-content:flex-start}[data-slot='sidebar.footer.action']:has(.ci-trigger[data-wide=true]){display:flex;flex-direction:column;flex:1;min-width:0;width:100%}.ci-trigger[data-wide=false]{width:36px;height:36px;justify-content:center;padding:0;border-radius:50%}.ci-trigger svg{flex-shrink:0}.ci-trigger:hover{background:var(--dsw-alias-interactive-bg-hover)}
.ci-panel{display:flex;flex:1 1 auto;flex-direction:column;width:100%;height:100%;min-width:0;min-height:0;background:var(--ci-bg);overflow:hidden}
.ci-header{flex:none;padding:20px 20px 16px;border-bottom:1px solid var(--dsw-alias-border-l2)}.ci-header h2{margin:0;font-size:20px;font-weight:600;line-height:1.4}.ci-subtitle{margin:4px 0 0;color:var(--ci-muted);font-size:13px}.ci-scroll{padding:20px;overflow:auto;scrollbar-width:thin;scrollbar-color:var(--dsw-alias-border-l2) transparent;min-height:0;overscroll-behavior:contain}
.ci-toolbar,.ci-actions,.ci-monthnav{display:flex;align-items:center;gap:8px}.ci-toolbar{justify-content:space-between;margin-bottom:20px;flex-wrap:wrap}.ci-filter{position:relative;min-width:0;max-width:220px;flex:1}.ci-filter>svg{position:absolute;right:12px;top:50%;transform:translateY(-50%);pointer-events:none;color:var(--ci-muted)}.ci-button,.ci-icon,.ci-select{border:0;background:var(--dsw-alias-interactive-bg-hover);border-radius:9px;min-height:34px;padding:6px 12px;display:inline-flex;align-items:center;justify-content:center;gap:6px}.ci-icon{width:34px;padding:6px;flex-shrink:0;background:transparent}.ci-button:hover,.ci-icon:hover{background:var(--dsw-alias-interactive-bg-active)}.ci-primary{background:var(--ci-fg);color:var(--ci-bg)!important}.ci-primary:hover{opacity:.85;background:var(--ci-fg)}.ci-danger{color:var(--dsw-alias-state-error-primary)!important}.ci-select{appearance:none;-webkit-appearance:none;width:100%;display:block;text-overflow:ellipsis;border:1px solid var(--dsw-alias-border-l2);padding:6px 36px 6px 12px;background:transparent;color:var(--ci-fg);cursor:pointer}.ci-select:hover{background:var(--dsw-alias-interactive-bg-hover)}.ci-select:focus-visible{outline:2px solid var(--dsw-alias-label-secondary);outline-offset:2px}.ci-select option{background:var(--ci-bg);color:var(--ci-fg)}
.ci-form{display:flex;flex-direction:column;gap:10px;padding:16px 0 20px;border-bottom:1px solid var(--dsw-alias-border-l2);margin-bottom:20px}.ci-form label{font-weight:500}.ci-form input{width:100%;min-height:40px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:8px 12px;background:transparent;caret-color:var(--ci-fg)}.ci-form input::placeholder{color:var(--ci-muted)}.ci-form .ci-actions{justify-content:flex-end}.ci-confirm{padding:16px 0;border-bottom:1px solid var(--dsw-alias-border-l2);margin-bottom:20px}.ci-confirm h3{margin:0;font-size:15px;overflow-wrap:anywhere}.ci-confirm p{color:var(--ci-muted);font-size:13px;margin:8px 0 12px}
.ci-monthnav{justify-content:space-between;margin:8px 0 20px}.ci-monthnav h3{font-size:19px;font-weight:600;line-height:1.4;margin:0;font-variant-numeric:tabular-nums}.ci-calendar{width:100%;border-collapse:separate;border-spacing:4px;table-layout:fixed}.ci-calendar th{color:var(--ci-muted);font-size:12px;font-weight:400;height:28px}.ci-calendar td{padding:0;text-align:center}.ci-day{width:100%;height:56px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;background:transparent;border:1px solid transparent;border-radius:10px;font-variant-numeric:tabular-nums}.ci-day:hover{background:var(--dsw-alias-interactive-bg-hover)}.ci-day[data-done=true]{background:var(--dsw-alias-interactive-bg-hover)}.ci-day[data-selected=true]{border-color:var(--ci-fg);background:var(--dsw-alias-interactive-bg-active)}.ci-day[data-today=true] .ci-date{font-weight:700;text-decoration:underline;text-underline-offset:4px}.ci-day[data-future=true]{color:var(--ci-muted)}.ci-day small{font-size:10px;color:var(--ci-muted);line-height:14px;display:flex;align-items:center;height:14px}.ci-date{font-size:14px}.ci-hint{color:var(--ci-muted);font-size:11px;margin:12px 0 0}.ci-detail{margin-top:28px;border-top:1px solid var(--dsw-alias-border-l2);padding-top:20px}.ci-detailhead{display:flex;align-items:baseline;justify-content:space-between;gap:8px;flex-wrap:wrap;margin-bottom:8px}.ci-detailhead h3{font-size:15px;font-weight:600;margin:0}.ci-detailhead span{color:var(--ci-muted);font-size:12px}.ci-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid var(--dsw-alias-border-l2)}.ci-row-name{min-width:0;flex:1;overflow-wrap:anywhere}.ci-row .ci-icon{width:28px;height:28px;min-height:28px}.ci-toggle{flex-shrink:0;width:28px;height:28px;display:grid;place-items:center;border:1px solid var(--dsw-alias-border-l2);border-radius:50%;background:transparent}.ci-toggle[aria-checked=true]{background:var(--ci-fg);color:var(--ci-bg);border-color:transparent}
.ci-empty{text-align:center;padding:52px 12px}.ci-empty>.ci-empty-icon{color:var(--ci-muted);margin-bottom:14px}.ci-button svg{flex-shrink:0}.ci-empty h3{font-size:18px;font-weight:500;margin:0 0 8px}.ci-empty p{color:var(--ci-muted);margin:0 0 24px;font-size:13px}.ci-alert{display:flex;align-items:center;justify-content:space-between;gap:12px;color:var(--dsw-alias-state-error-primary);padding:12px 0;font-size:13px}.ci-status{padding:20px 0;color:var(--ci-muted)}.ci-footer{border-top:1px solid var(--dsw-alias-border-l2);padding:12px 24px;color:var(--ci-muted);font-size:11px;margin-top:auto}
@media(max-width:600px){.ci-header{padding:18px 16px 14px}.ci-scroll{padding:16px 12px 20px}.ci-day{height:50px}.ci-filter{max-width:180px}.ci-footer{padding:12px 16px}}
`;
//# sourceMappingURL=styles.js.map
