/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CheckinResult, CreateTopic, DeleteResult, ExportDataRequest, ExportDataResult, ImportDataRequest, ImportDataResult, MonthRequest, MonthResult, QueryCheckins, QueryResult, SetCheckin, Topic, TopicList, TopicRequest, UpdateTopic } from 'dsh-checkin/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636865636b696e {
    create: (request: CreateTopic, signal?: AbortSignal) => Promise<RemoteResult<Topic>>
    delete: (request: TopicRequest, signal?: AbortSignal) => Promise<RemoteResult<DeleteResult>>
    exportData: (_request: ExportDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ExportDataResult>>
    importData: (request: ImportDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportDataResult>>
    list: (signal?: AbortSignal) => Promise<RemoteResult<TopicList>>
    month: (request: MonthRequest, signal?: AbortSignal) => Promise<RemoteResult<MonthResult>>
    query: (request: QueryCheckins, signal?: AbortSignal) => Promise<RemoteResult<QueryResult>>
    set: (request: SetCheckin, signal?: AbortSignal) => Promise<RemoteResult<CheckinResult>>
    update: (request: UpdateTopic, signal?: AbortSignal) => Promise<RemoteResult<Topic>>
  }
  interface TypertRemoteMap {
    'checkin/create': (request: CreateTopic, signal?: AbortSignal) => Promise<RemoteResult<Topic>>
    'checkin/delete': (request: TopicRequest, signal?: AbortSignal) => Promise<RemoteResult<DeleteResult>>
    'checkin/exportData': (_request: ExportDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ExportDataResult>>
    'checkin/importData': (request: ImportDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportDataResult>>
    'checkin/list': (signal?: AbortSignal) => Promise<RemoteResult<TopicList>>
    'checkin/month': (request: MonthRequest, signal?: AbortSignal) => Promise<RemoteResult<MonthResult>>
    'checkin/query': (request: QueryCheckins, signal?: AbortSignal) => Promise<RemoteResult<QueryResult>>
    'checkin/set': (request: SetCheckin, signal?: AbortSignal) => Promise<RemoteResult<CheckinResult>>
    'checkin/update': (request: UpdateTopic, signal?: AbortSignal) => Promise<RemoteResult<Topic>>
  }
  interface TypertRemoteNamespaceMap {
    'checkin': TypertRemoteNamespace$636865636b696e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
