/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_checkin_checkin_connect_parameter_0$schema = z.object({
  'databaseId': z.string(),
  'tableName': z.string(),
  'recordsTableName': z.string(),
})
const dsh_checkin_checkin_connect_result$schema = z.object({
  'phase': z.union([z.literal("login"), z.literal("setup"), z.literal("connected"), z.literal("invalid")]),
  'source': z.union([z.literal("host"), z.literal("saved"), z.literal("none")]),
  'revision': z.string(),
  'writable': z.boolean(),
  'databaseId': z.union([z.undefined(), z.string()]).optional(),
  'tableName': z.union([z.undefined(), z.string()]).optional(),
  'recordsTableName': z.union([z.undefined(), z.string()]).optional(),
  'pendingDatabaseName': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_checkin_checkin_connection_result$schema = z.object({
  'phase': z.union([z.literal("login"), z.literal("setup"), z.literal("connected"), z.literal("invalid")]),
  'source': z.union([z.literal("host"), z.literal("saved"), z.literal("none")]),
  'revision': z.string(),
  'writable': z.boolean(),
  'databaseId': z.union([z.undefined(), z.string()]).optional(),
  'tableName': z.union([z.undefined(), z.string()]).optional(),
  'recordsTableName': z.union([z.undefined(), z.string()]).optional(),
  'pendingDatabaseName': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_checkin_checkin_create_parameter_0$schema = z.object({
  'name': z.string(),
})
const dsh_checkin_checkin_create_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})
const dsh_checkin_checkin_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
})
const dsh_checkin_checkin_delete_result$schema = z.object({
  'topic': z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}),
  'deletedRecords': z.number(),
})
const dsh_checkin_checkin_initialize_parameter_0$schema = z.object({
  'databaseId': z.union([z.undefined(), z.string()]).optional(),
  'databaseName': z.union([z.undefined(), z.string()]).optional(),
  'tableName': z.string(),
  'recordsTableName': z.string(),
  'useExistingTopics': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'useExistingRecords': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'confirmed': z.boolean(),
})
const dsh_checkin_checkin_initialize_result$schema = z.object({
  'phase': z.union([z.literal("login"), z.literal("setup"), z.literal("connected"), z.literal("invalid")]),
  'source': z.union([z.literal("host"), z.literal("saved"), z.literal("none")]),
  'revision': z.string(),
  'writable': z.boolean(),
  'databaseId': z.union([z.undefined(), z.string()]).optional(),
  'tableName': z.union([z.undefined(), z.string()]).optional(),
  'recordsTableName': z.union([z.undefined(), z.string()]).optional(),
  'pendingDatabaseName': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_checkin_checkin_list_result$schema = z.object({
  'today': z.string(),
  'timeZone': z.string(),
  'topics': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
})
const dsh_checkin_checkin_login_parameter_0$schema = z.object({
  'apiKey': z.string(),
})
const dsh_checkin_checkin_login_result$schema = z.object({
  'phase': z.union([z.literal("login"), z.literal("setup"), z.literal("connected"), z.literal("invalid")]),
  'source': z.union([z.literal("host"), z.literal("saved"), z.literal("none")]),
  'revision': z.string(),
  'writable': z.boolean(),
  'databaseId': z.union([z.undefined(), z.string()]).optional(),
  'tableName': z.union([z.undefined(), z.string()]).optional(),
  'recordsTableName': z.union([z.undefined(), z.string()]).optional(),
  'pendingDatabaseName': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_checkin_checkin_logout_result$schema = z.object({
  'phase': z.union([z.literal("login"), z.literal("setup"), z.literal("connected"), z.literal("invalid")]),
  'source': z.union([z.literal("host"), z.literal("saved"), z.literal("none")]),
  'revision': z.string(),
  'writable': z.boolean(),
  'databaseId': z.union([z.undefined(), z.string()]).optional(),
  'tableName': z.union([z.undefined(), z.string()]).optional(),
  'recordsTableName': z.union([z.undefined(), z.string()]).optional(),
  'pendingDatabaseName': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_checkin_checkin_month_parameter_0$schema = z.object({
  'month': z.union([z.undefined(), z.string()]).optional(),
})
const dsh_checkin_checkin_month_result$schema = z.object({
  'month': z.string(),
  'refreshIntervalMs': z.number(),
  'today': z.string(),
  'timeZone': z.string(),
  'from': z.string(),
  'to': z.string(),
  'topics': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
  'completions': z.array(z.object({
  'topicId': z.intersection(z.string(), z.unknown()),
  'date': z.string(),
})),
})
const dsh_checkin_checkin_query_parameter_0$schema = z.object({
  'from': z.string(),
  'to': z.string(),
  'topicId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).optional(),
})
const dsh_checkin_checkin_query_result$schema = z.object({
  'today': z.string(),
  'timeZone': z.string(),
  'from': z.string(),
  'to': z.string(),
  'topics': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
  'completions': z.array(z.object({
  'topicId': z.intersection(z.string(), z.unknown()),
  'date': z.string(),
})),
})
const dsh_checkin_checkin_resources_result$schema = z.object({
  'enabled': z.boolean(),
  'limits': z.object({
  'maxDatabases': z.number(),
  'maxTables': z.number(),
  'maxBytes': z.number(),
}),
  'databases': z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'status': z.union([z.literal("ready"), z.literal("provisioning"), z.literal("deleting")]),
  'usedBytes': z.number(),
  'tables': z.array(z.object({
  'name': z.string(),
})),
})),
})
const dsh_checkin_checkin_set_parameter_0$schema = z.object({
  'topicId': z.intersection(z.string(), z.unknown()),
  'date': z.union([z.undefined(), z.string()]).optional(),
  'completed': z.boolean(),
})
const dsh_checkin_checkin_set_result$schema = z.object({
  'topic': z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}),
  'date': z.string(),
  'completed': z.boolean(),
})
const dsh_checkin_checkin_update_parameter_0$schema = z.object({
  'name': z.string(),
  'id': z.intersection(z.string(), z.unknown()),
})
const dsh_checkin_checkin_update_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})

export const TYPERT = {
  package: 'dsh-checkin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-checkin#checkin/connect',
      service: 'checkin',
      namespace: 'checkin',
      method: 'connect',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#ConnectRequest',
            schema: dsh_checkin_checkin_connect_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ConnectionState',
        schema: dsh_checkin_checkin_connect_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":35,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/connection',
      service: 'checkin',
      namespace: 'checkin',
      method: 'connection',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ConnectionState',
        schema: dsh_checkin_checkin_connection_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":29,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/create',
      service: 'checkin',
      namespace: 'checkin',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#CreateTopic',
            schema: dsh_checkin_checkin_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#Topic',
        schema: dsh_checkin_checkin_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":45,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/delete',
      service: 'checkin',
      namespace: 'checkin',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#TopicRequest',
            schema: dsh_checkin_checkin_delete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#DeleteResult',
        schema: dsh_checkin_checkin_delete_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":51,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/initialize',
      service: 'checkin',
      namespace: 'checkin',
      method: 'initialize',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#InitializeRequest',
            schema: dsh_checkin_checkin_initialize_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ConnectionState',
        schema: dsh_checkin_checkin_initialize_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":37,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/list',
      service: 'checkin',
      namespace: 'checkin',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#TopicList',
        schema: dsh_checkin_checkin_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":42,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/login',
      service: 'checkin',
      namespace: 'checkin',
      method: 'login',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#LoginRequest',
            schema: dsh_checkin_checkin_login_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ConnectionState',
        schema: dsh_checkin_checkin_login_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":31,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/logout',
      service: 'checkin',
      namespace: 'checkin',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ConnectionState',
        schema: dsh_checkin_checkin_logout_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":39,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/month',
      service: 'checkin',
      namespace: 'checkin',
      method: 'month',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#MonthRequest',
            schema: dsh_checkin_checkin_month_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#MonthResult',
        schema: dsh_checkin_checkin_month_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":60,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/query',
      service: 'checkin',
      namespace: 'checkin',
      method: 'query',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#QueryCheckins',
            schema: dsh_checkin_checkin_query_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#QueryResult',
        schema: dsh_checkin_checkin_query_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":57,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/resources',
      service: 'checkin',
      namespace: 'checkin',
      method: 'resources',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#DatabaseResources',
        schema: dsh_checkin_checkin_resources_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":33,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/set',
      service: 'checkin',
      namespace: 'checkin',
      method: 'set',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#SetCheckin',
            schema: dsh_checkin_checkin_set_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#CheckinResult',
        schema: dsh_checkin_checkin_set_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":54,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/update',
      service: 'checkin',
      namespace: 'checkin',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#UpdateTopic',
            schema: dsh_checkin_checkin_update_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#Topic',
        schema: dsh_checkin_checkin_update_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":48,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "checkin",
        "exportName": "CheckinService",
        "members": [
          {
            "kind": "method",
            "name": "connection",
            "signature": "@Remote async connection(signal: AbortSignal): Promise<ConnectionState>"
          },
          {
            "kind": "method",
            "name": "login",
            "signature": "@Remote async login(request: LoginRequest, signal: AbortSignal): Promise<ConnectionState>"
          },
          {
            "kind": "method",
            "name": "resources",
            "signature": "@Remote async resources(signal: AbortSignal): Promise<DatabaseResources>"
          },
          {
            "kind": "method",
            "name": "connect",
            "signature": "@Remote async connect(request: ConnectRequest, signal: AbortSignal): Promise<ConnectionState>"
          },
          {
            "kind": "method",
            "name": "initialize",
            "signature": "@Remote async initialize(request: InitializeRequest, signal: AbortSignal): Promise<ConnectionState>"
          },
          {
            "kind": "method",
            "name": "logout",
            "signature": "@Remote async logout(signal: AbortSignal): Promise<ConnectionState>"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote async list(signal: AbortSignal): Promise<TopicList>",
            "jsDoc": "/** @param signal - Request cancellation. @returns Catalog and Beijing date. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote async create(request: CreateTopic, signal: AbortSignal): Promise<Topic>",
            "jsDoc": "/** @param request - New name. @param signal - Cancellation. @returns Created topic. */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote async update(request: UpdateTopic, signal: AbortSignal): Promise<Topic>",
            "jsDoc": "/** @param request - Topic and new name. @param signal - Cancellation. @returns Updated topic. */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote async delete(request: TopicRequest, signal: AbortSignal): Promise<DeleteResult>",
            "jsDoc": "/** @param request - Topic to delete. @param signal - Cancellation. @returns Removed topic and count. */"
          },
          {
            "kind": "method",
            "name": "set",
            "signature": "@Remote async set(request: SetCheckin, signal: AbortSignal): Promise<CheckinResult>",
            "jsDoc": "/** @param request - Desired completion status. @param signal - Cancellation. @returns Persisted status. */"
          },
          {
            "kind": "method",
            "name": "query",
            "signature": "@Remote async query(request: QueryCheckins, signal: AbortSignal): Promise<QueryResult>",
            "jsDoc": "/** @param request - Inclusive dates. @param signal - Cancellation. @returns Sparse completions. */"
          },
          {
            "kind": "method",
            "name": "month",
            "signature": "@Remote async month(request: MonthRequest, signal: AbortSignal): Promise<MonthResult>",
            "jsDoc": "/** @param request - Month, defaulting to Beijing's current month. @param signal - Cancellation. @returns Calendar snapshot. */"
          }
        ],
        "types": [
          {
            "name": "CheckinResult",
            "declaration": "export interface CheckinResult {\n    topic: Topic;\n    date: string;\n    completed: boolean;\n}"
          },
          {
            "name": "Completion",
            "declaration": "export interface Completion {\n    topicId: TopicId;\n    date: string;\n}"
          },
          {
            "name": "ConnectionState",
            "declaration": "export interface ConnectionState {\n    phase: 'login' | 'setup' | 'connected' | 'invalid';\n    source: 'host' | 'saved' | 'none';\n    revision: string;\n    writable: boolean;\n    databaseId?: string;\n    tableName?: string;\n    recordsTableName?: string;\n    pendingDatabaseName?: string;\n}"
          },
          {
            "name": "ConnectRequest",
            "declaration": "export interface ConnectRequest {\n    databaseId: string;\n    tableName: string;\n    recordsTableName: string;\n}"
          },
          {
            "name": "CreateTopic",
            "declaration": "export interface CreateTopic {\n    name: string;\n}"
          },
          {
            "name": "DatabaseResources",
            "declaration": "export interface DatabaseResources {\n    enabled: boolean;\n    limits: { maxDatabases: number; maxTables: number; maxBytes: number; };\n    databases: { id: string; name: string; status: 'ready' | 'provisioning' | 'deleting'; usedBytes: number; tables: { name: string; }[]; }[];\n}"
          },
          {
            "name": "DeleteResult",
            "declaration": "export interface DeleteResult {\n    topic: Topic;\n    deletedRecords: number;\n}"
          },
          {
            "name": "InitializeRequest",
            "declaration": "export interface InitializeRequest {\n    databaseId?: string;\n    databaseName?: string;\n    tableName: string;\n    recordsTableName: string;\n    useExistingTopics?: boolean;\n    useExistingRecords?: boolean;\n    confirmed: boolean;\n}"
          },
          {
            "name": "LoginRequest",
            "declaration": "export interface LoginRequest {\n    apiKey: string;\n}"
          },
          {
            "name": "MonthRequest",
            "declaration": "export interface MonthRequest {\n    month?: string;\n}"
          },
          {
            "name": "MonthResult",
            "declaration": "export interface MonthResult extends QueryResult {\n    month: string;\n    refreshIntervalMs: number;\n}"
          },
          {
            "name": "QueryCheckins",
            "declaration": "export interface QueryCheckins {\n    from: string;\n    to: string;\n    topicId?: TopicId;\n}"
          },
          {
            "name": "QueryResult",
            "declaration": "export interface QueryResult {\n    today: string;\n    timeZone: string;\n    from: string;\n    to: string;\n    topics: Topic[];\n    completions: Completion[];\n}"
          },
          {
            "name": "SetCheckin",
            "declaration": "export interface SetCheckin {\n    topicId: TopicId;\n    date?: string;\n    completed: boolean;\n}"
          },
          {
            "name": "Topic",
            "declaration": "export interface Topic {\n    id: TopicId;\n    name: string;\n    createdAt: string;\n    updatedAt: string;\n}"
          },
          {
            "name": "TopicId",
            "declaration": "export type TopicId = Branded<'CheckinTopicId'>;"
          },
          {
            "name": "TopicList",
            "declaration": "export interface TopicList {\n    today: string;\n    timeZone: string;\n    topics: Topic[];\n}"
          },
          {
            "name": "TopicRequest",
            "declaration": "export interface TopicRequest {\n    id: TopicId;\n}"
          },
          {
            "name": "UpdateTopic",
            "declaration": "export interface UpdateTopic extends TopicRequest {\n    name: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
