/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let dsh_checkin_checkin_create_parameter_0$schema$value
const dsh_checkin_checkin_create_parameter_0$schema = () => (dsh_checkin_checkin_create_parameter_0$schema$value ??= z.object({
  'name': z.string(),
}))
let dsh_checkin_checkin_create_result$schema$value
const dsh_checkin_checkin_create_result$schema = () => (dsh_checkin_checkin_create_result$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}))
let dsh_checkin_checkin_delete_parameter_0$schema$value
const dsh_checkin_checkin_delete_parameter_0$schema = () => (dsh_checkin_checkin_delete_parameter_0$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()),
}))
let dsh_checkin_checkin_delete_result$schema$value
const dsh_checkin_checkin_delete_result$schema = () => (dsh_checkin_checkin_delete_result$schema$value ??= z.object({
  'topic': z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}),
  'deletedRecords': z.number(),
}))
let dsh_checkin_checkin_exportData_parameter_0$schema$value
const dsh_checkin_checkin_exportData_parameter_0$schema = () => (dsh_checkin_checkin_exportData_parameter_0$schema$value ??= z.object({
  'unused': z.undefined().optional(),
}))
let dsh_checkin_checkin_exportData_result$schema$value
const dsh_checkin_checkin_exportData_result$schema = () => (dsh_checkin_checkin_exportData_result$schema$value ??= z.object({
  'filename': z.string(),
  'json': z.string(),
}))
let dsh_checkin_checkin_importData_parameter_0$schema$value
const dsh_checkin_checkin_importData_parameter_0$schema = () => (dsh_checkin_checkin_importData_parameter_0$schema$value ??= z.object({
  'json': z.string(),
}))
let dsh_checkin_checkin_importData_result$schema$value
const dsh_checkin_checkin_importData_result$schema = () => (dsh_checkin_checkin_importData_result$schema$value ??= z.object({
  'importedTopics': z.number(),
  'importedCompletions': z.number(),
  'skippedTopics': z.number(),
}))
let dsh_checkin_checkin_list_result$schema$value
const dsh_checkin_checkin_list_result$schema = () => (dsh_checkin_checkin_list_result$schema$value ??= z.object({
  'today': z.string(),
  'timeZone': z.string(),
  'topics': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
}))
let dsh_checkin_checkin_month_parameter_0$schema$value
const dsh_checkin_checkin_month_parameter_0$schema = () => (dsh_checkin_checkin_month_parameter_0$schema$value ??= z.object({
  'month': z.union([z.undefined(), z.string()]).optional(),
}))
let dsh_checkin_checkin_month_result$schema$value
const dsh_checkin_checkin_month_result$schema = () => (dsh_checkin_checkin_month_result$schema$value ??= z.object({
  'month': z.string(),
  'refreshIntervalMs': z.number(),
  'today': z.string(),
  'timeZone': z.string(),
  'from': z.string(),
  'to': z.string(),
  'topics': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
  'completions': z.array(z.object({
  'topicId': z.intersection(z.string(), z.unknown()),
  'date': z.string(),
})),
}))
let dsh_checkin_checkin_query_parameter_0$schema$value
const dsh_checkin_checkin_query_parameter_0$schema = () => (dsh_checkin_checkin_query_parameter_0$schema$value ??= z.object({
  'from': z.string(),
  'to': z.string(),
  'topicId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).optional(),
}))
let dsh_checkin_checkin_query_result$schema$value
const dsh_checkin_checkin_query_result$schema = () => (dsh_checkin_checkin_query_result$schema$value ??= z.object({
  'today': z.string(),
  'timeZone': z.string(),
  'from': z.string(),
  'to': z.string(),
  'topics': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
  'completions': z.array(z.object({
  'topicId': z.intersection(z.string(), z.unknown()),
  'date': z.string(),
})),
}))
let dsh_checkin_checkin_set_parameter_0$schema$value
const dsh_checkin_checkin_set_parameter_0$schema = () => (dsh_checkin_checkin_set_parameter_0$schema$value ??= z.object({
  'topicId': z.intersection(z.string(), z.unknown()),
  'date': z.union([z.undefined(), z.string()]).optional(),
  'completed': z.boolean(),
}))
let dsh_checkin_checkin_set_result$schema$value
const dsh_checkin_checkin_set_result$schema = () => (dsh_checkin_checkin_set_result$schema$value ??= z.object({
  'topic': z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}),
  'date': z.string(),
  'completed': z.boolean(),
}))
let dsh_checkin_checkin_update_parameter_0$schema$value
const dsh_checkin_checkin_update_parameter_0$schema = () => (dsh_checkin_checkin_update_parameter_0$schema$value ??= z.object({
  'name': z.string(),
  'id': z.intersection(z.string(), z.unknown()),
}))
let dsh_checkin_checkin_update_result$schema$value
const dsh_checkin_checkin_update_result$schema = () => (dsh_checkin_checkin_update_result$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}))

export const TYPERT = {
  package: 'dsh-checkin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-checkin#checkin/create',
      service: 'checkin',
      namespace: 'checkin',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#CreateTopic',
            create: dsh_checkin_checkin_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#Topic',
        create: dsh_checkin_checkin_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":33,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/delete',
      service: 'checkin',
      namespace: 'checkin',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#TopicRequest',
            create: dsh_checkin_checkin_delete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#DeleteResult',
        create: dsh_checkin_checkin_delete_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":39,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/exportData',
      service: 'checkin',
      namespace: 'checkin',
      method: 'exportData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#ExportDataRequest',
            create: dsh_checkin_checkin_exportData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ExportDataResult',
        create: dsh_checkin_checkin_exportData_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":55,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/importData',
      service: 'checkin',
      namespace: 'checkin',
      method: 'importData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#ImportDataRequest',
            create: dsh_checkin_checkin_importData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#ImportDataResult',
        create: dsh_checkin_checkin_importData_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":61,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/list',
      service: 'checkin',
      namespace: 'checkin',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#TopicList',
        create: dsh_checkin_checkin_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":30,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/month',
      service: 'checkin',
      namespace: 'checkin',
      method: 'month',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#MonthRequest',
            create: dsh_checkin_checkin_month_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#MonthResult',
        create: dsh_checkin_checkin_month_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":48,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/query',
      service: 'checkin',
      namespace: 'checkin',
      method: 'query',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#QueryCheckins',
            create: dsh_checkin_checkin_query_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#QueryResult',
        create: dsh_checkin_checkin_query_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":45,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/set',
      service: 'checkin',
      namespace: 'checkin',
      method: 'set',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#SetCheckin',
            create: dsh_checkin_checkin_set_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#CheckinResult',
        create: dsh_checkin_checkin_set_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":42,"column":9},
    },
    {
      id: 'dsh-checkin#checkin/update',
      service: 'checkin',
      namespace: 'checkin',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-checkin/types#UpdateTopic',
            create: dsh_checkin_checkin_update_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-checkin/types#Topic',
        create: dsh_checkin_checkin_update_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-checkin/src/index.ts","line":36,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Global SQLite service; no session or workspace partitioning.",
        "summary": "Global SQLite service; no session or workspace partitioning.",
        "tags": [],
        "jsDoc": "/** Global SQLite service; no session or workspace partitioning. */",
        "key": "checkin",
        "exportName": "CheckinService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote async list(signal: AbortSignal): Promise<TopicList>",
            "jsDoc": "/** @param signal - Request cancellation. @returns Catalog and Beijing date. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote async create(request: CreateTopic, signal: AbortSignal): Promise<Topic>",
            "jsDoc": "/** @param request - New name. @param signal - Cancellation. @returns Created topic. */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote async update(request: UpdateTopic, signal: AbortSignal): Promise<Topic>",
            "jsDoc": "/** @param request - Topic and new name. @param signal - Cancellation. @returns Updated topic. */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote async delete(request: TopicRequest, signal: AbortSignal): Promise<DeleteResult>",
            "jsDoc": "/** @param request - Topic to delete. @param signal - Cancellation. @returns Removed topic and count. */"
          },
          {
            "kind": "method",
            "name": "set",
            "signature": "@Remote async set(request: SetCheckin, signal: AbortSignal): Promise<CheckinResult>",
            "jsDoc": "/** @param request - Desired completion status. @param signal - Cancellation. @returns Persisted status. */"
          },
          {
            "kind": "method",
            "name": "query",
            "signature": "@Remote async query(request: QueryCheckins, signal: AbortSignal): Promise<QueryResult>",
            "jsDoc": "/** @param request - Inclusive dates. @param signal - Cancellation. @returns Sparse completions. */"
          },
          {
            "kind": "method",
            "name": "month",
            "signature": "@Remote async month(request: MonthRequest, signal: AbortSignal): Promise<MonthResult>",
            "jsDoc": "/** @param request - Month, defaulting to Beijing's current month. @param signal - Cancellation. @returns Calendar snapshot. */"
          },
          {
            "kind": "method",
            "name": "exportData",
            "signature": "@Remote async exportData(_request: ExportDataRequest, signal: AbortSignal): Promise<ExportDataResult>",
            "jsDoc": "/** @param _request - Empty request. @param signal - Cancellation. @returns Portable JSON backup. */"
          },
          {
            "kind": "method",
            "name": "importData",
            "signature": "@Remote async importData(request: ImportDataRequest, signal: AbortSignal): Promise<ImportDataResult>",
            "jsDoc": "/** @param request - Confirmed backup. @param signal - Cancellation. @returns Incremental import counts. */"
          }
        ],
        "types": [
          {
            "name": "CheckinResult",
            "declaration": "export interface CheckinResult {\n    topic: Topic;\n    date: string;\n    completed: boolean;\n}"
          },
          {
            "name": "Completion",
            "declaration": "export interface Completion {\n    topicId: TopicId;\n    date: string;\n}"
          },
          {
            "name": "CreateTopic",
            "declaration": "export interface CreateTopic {\n    name: string;\n}"
          },
          {
            "name": "DeleteResult",
            "declaration": "export interface DeleteResult {\n    topic: Topic;\n    deletedRecords: number;\n}"
          },
          {
            "name": "ExportDataRequest",
            "declaration": "export interface ExportDataRequest {\n    unused?: undefined;\n}"
          },
          {
            "name": "ExportDataResult",
            "declaration": "export interface ExportDataResult {\n    filename: string;\n    json: string;\n}"
          },
          {
            "name": "ImportDataRequest",
            "declaration": "export interface ImportDataRequest {\n    json: string;\n}"
          },
          {
            "name": "ImportDataResult",
            "declaration": "export interface ImportDataResult {\n    importedTopics: number;\n    importedCompletions: number;\n    skippedTopics: number;\n}"
          },
          {
            "name": "MonthRequest",
            "declaration": "export interface MonthRequest {\n    month?: string;\n}"
          },
          {
            "name": "MonthResult",
            "declaration": "export interface MonthResult extends QueryResult {\n    month: string;\n    refreshIntervalMs: number;\n}"
          },
          {
            "name": "QueryCheckins",
            "declaration": "export interface QueryCheckins {\n    from: string;\n    to: string;\n    topicId?: TopicId;\n}"
          },
          {
            "name": "QueryResult",
            "declaration": "export interface QueryResult {\n    today: string;\n    timeZone: string;\n    from: string;\n    to: string;\n    topics: Topic[];\n    completions: Completion[];\n}"
          },
          {
            "name": "SetCheckin",
            "declaration": "export interface SetCheckin {\n    topicId: TopicId;\n    date?: string;\n    completed: boolean;\n}"
          },
          {
            "name": "Topic",
            "declaration": "export interface Topic {\n    id: TopicId;\n    name: string;\n    createdAt: string;\n    updatedAt: string;\n}"
          },
          {
            "name": "TopicId",
            "declaration": "export type TopicId = Branded<'CheckinTopicId'>;"
          },
          {
            "name": "TopicList",
            "declaration": "export interface TopicList {\n    today: string;\n    timeZone: string;\n    topics: Topic[];\n}"
          },
          {
            "name": "TopicRequest",
            "declaration": "export interface TopicRequest {\n    id: TopicId;\n}"
          },
          {
            "name": "UpdateTopic",
            "declaration": "export interface UpdateTopic extends TopicRequest {\n    name: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
