import type { CheckinKey } from './locales.ts'

export function failureKey(error: string): CheckinKey {
  if (error.includes('credentials-unavailable')) return 'credentialsUnavailable'
  if (error.includes('managed-connection')) return 'managedError'
  if (error.includes('confirmation-required')) return 'confirmationRequired'
  if (error.includes('connection-changed')) return 'connectionChanged'
  if (error.includes('duplicate-name')) return 'duplicate'
  if (error.includes('invalid-name')) return 'invalidName'
  if (error.includes('topic-not-found')) return 'notFound'
  if (error.includes('future-date')) return 'future'
  if (error.includes('invalid-date') || error.includes('invalid-range')) return 'invalidDate'
  if (error.includes('invalid-config') || error.includes('database-not-found') || error.includes('table-not-found')) return 'databaseConfig'
  if (error.includes('unauthorized')) return 'unauthorized'
  if (error.includes('service-disabled') || error.includes('database-not-ready')) return 'databaseNotReady'
  if (error.includes('quota-exceeded')) return 'quota'
  if (error.includes('database-conflict')) return 'databaseConflict'
  if (error.includes('invalid-schema')) return 'invalidSchema'
  if (error.includes('query-rejected')) return 'queryRejected'
  if (error.includes('api-unavailable')) return 'apiUnavailable'
  if (error.includes('request-too-large')) return 'requestTooLarge'
  if (error.includes('concurrent-change')) return 'concurrentChange'
  if (error.includes('rate-limited')) return 'rateLimited'
  if (error.includes('write-uncertain')) return 'writeUncertain'
  if (error.includes('invalid-data') || error.includes('invalid-response')) return 'invalidData'
  if (error.includes('inconsistent-read')) return 'inconsistentRead'
  if (error.includes('service-unavailable')) return 'serviceUnavailable'
  return 'error'
}
